### PR TITLE
No hidden components and models

### PR DESCRIPTION
**Pull request by breathbath**

### CODE REVIEW

**Comment by Dysar** [comment]
I would not go with moving the entire `common` package into the `pkg` as there are internal functions that can mislead the user and/or be misused. Example: `NewClient`. There can be more, a review is needed here. 

Perhaps it would make sense to separate the package and make a part of it accessible for the users while keeping as much inner logic internal. 

I will review this and make the change in respect to the issue that was raised.

**Comment by breathbath** [comment]
your code is not functional - `customers.NewClient` requires `common.Client` which is not accessible from other packages so there is no chance to create it properly. Usage of internal components might lead to the issues like we have now. 
I need to finish my task but I've spent 2 days to adjust this library to make it work, but unfortunately with no luck so I would probably use the forked version.

**Comment by Dysar** [comment]
Ohh, then there is a lack of documentation. Will review also. Do the customer requests work with the api.Client object if that gets initialised and used for the requests? I will add the change tomorrow, perhaps then you could switch again if something will be needed.
17 мая 2020 г., 20:53 +0300, Andrey <notifications@github.com>, писал:

this code is not functional - customers.NewClient requires common.Client which is not accessible from other packages so there is no chance to create it properly. Usage of internal components might lead to the issues like we have now.
I need to finish my task but I've spent 2 days to adjust this library to make it work, but unfortunately with no luck so I would probably use the forked version.

**Comment by breathbath** [comment]
I see your point thanks - I am still bit lost in the amount of clients the library exposes. So it's not obvious why we have common.Client, api.Client and customers.Client ;-)

**Pull request closed without merging**
